### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by fnoop** [Akryum/vue-cli-plugin-apollo#2]
```
[dev] [mav@goodrobots-maverick ~/code/maverick-web]$ npm i -D vue-cli-plugin-apollo

> nodemon@1.14.12 postinstall /srv/maverick/code/maverick-web/node_modules/nodemon
> node -e "console.log('\u001b[32mLove nodemon? You can now support the project via the open collective:\u001b[22m\u001b[39m\n > \u001b[96m\u001b[1mhttps://opencollective.com/nodemon/donate\u001b[0m\n')" || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN vue-cli-plugin-apollo@0.2.1 requires a peer of @vue/cli-shared-utils@^3.0.0-alpha.12 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-upload-server@4.0.2 requires a peer of graphql@0.11 - 0.12 but none is installed. You must install peer dependencies yourself.
npm WARN subscriptions-transport-ws@0.9.5 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-playground-middleware-lambda@1.4.0 requires a peer of aws-lambda@^0.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-core@1.3.2 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-cache-control@0.0.9 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-tracing@0.1.3 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-extensions@0.0.7 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ vue-cli-plugin-apollo@0.2.1
added 427 packages in 21.166s
[dev] [mav@goodrobots-maverick ~/code/maverick-web]$ vue invoke apollo
 ERROR  Error: Cannot find module '@vue/cli-shared-utils'
Error: Cannot find module '@vue/cli-shared-utils'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/maverick/code/maverick-web/node_modules/vue-cli-plugin-apollo/generator/index.js:4:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by fnoop** [comment]
If I add the deps by hand, then:
```
[dev] [mav@goodrobots-maverick ~/code/maverick-web]$ vue invoke apollo
? Add a GraphQL API Server? No

⠋  Invoking generator for vue-cli-plugin-apollo... ERROR  ReferenceError: ejs:16
    14| const GRAPHQL_PATH = process.env.VUE_APP_GRAPHQL_PATH || '/graphql'
    15| const GRAPHQL_SUBSCRIPTIONS_PATH = process.env.VUE_APP_GRAPHQL_SUBSCRIPTIONS_PATH || '/graphql'
 >> 16| const GRAPHQL_PERSIST_QUERIES = <%= addApolloEngine %>
           17|
    18| // Create the apollo client
    19| export function createApolloClient ({ ssr }) {

addApolloEngine is not defined
ReferenceError: ejs:16
    14| const GRAPHQL_PATH = process.env.VUE_APP_GRAPHQL_PATH || '/graphql'
    15| const GRAPHQL_SUBSCRIPTIONS_PATH = process.env.VUE_APP_GRAPHQL_SUBSCRIPTIONS_PATH || '/graphql'
 >> 16| const GRAPHQL_PERSIST_QUERIES = <%= addApolloEngine %>
    17|
    18| // Create the apollo client
    19| export function createApolloClient ({ ssr }) {

addApolloEngine is not defined
    at eval (eval at compile (/usr/lib/node_modules/@vue/cli/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:26)
    at returnedFn (/usr/lib/node_modules/@vue/cli/node_modules/ejs/lib/ejs.js:580:17)
    at Object.exports.render (/usr/lib/node_modules/@vue/cli/node_modules/ejs/lib/ejs.js:384:37)
    at renderFile (/usr/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:214:14)
    at _injectFileMiddleware (/usr/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:158:27)
    at <anonymous>
```

**Comment by ameistad** [comment]
I was able to reproduce this issue when choosing not to install the GraphQL API server at the prompt.

**Comment by Akryum** [comment]
You need to use vue-cli 3.x and a project created with it;

**Comment by ameistad** [comment]
I'm running vue-cli version 3.0.0-alpha.13 and I'm still getting that exact error.

The issue seems to be this line in apollo.js
`const GRAPHQL_PERSIST_QUERIES = <%= addApolloEngine %>`

When you select not to add the GraphQL API Server the ejs variable addApolloEngine is not available.

**Comment by fnoop** [comment]
Yes confirmed I was using vue-cli 3.0.0-alpha13 and this was with a brand new template.

**Comment by kurisutofu** [comment]
Hi,
I'm getting the same error.
I'm using Vue 3.0.1 and only ran "npm init" before "vue add apollo" .

**Comment by Akryum** [comment]
You need to create a Vue CLI 3 project with `vue create`.

Le mar. 4 sept. 2018 à 11:34, kurisutofu <notifications@github.com> a
écrit :

**Comment by kurisutofu** [comment]
I tried `npm init`, followed by `vue create testapp` and finally `add apollo`.
I still get the error.
 
Am I doing it wrong?

**Comment by alexandermikuta** [comment]
@kurisutofu Did you cd into folder testapp before `vue add apollo`?

**Comment by kurisutofu** [comment]
@alexandermikuta , yes I did it ...

But anyway, I've started from scratch by doing the following.

1 - vue create apollotest 
2 - cd apollotest
3 - vue add apollo

Now I see a different error below.
`'vue-cli-plugin-apollo' should be listed in the project's dependencies, not devDependencies (import/no-extraneous-dependencies) at src\vue-apollo.js:3:1`

**Comment by kurisutofu** [comment]
nevermind.
I added vue-cli-plugin-apollo to the dependencies in package.json and now all looks fine.
