### ISSUE TITLE
 Error while loading rule 'graphql/template-strings': Must provide .graphqlconfig file or pass in `schemaJson` option with schema object or `schemaJsonFilepath` with absolute path to the json file.

### ISSUE THREAD

**Issue by mekhami** [Akryum/vue-cli-plugin-apollo#21]
Receiving this error even though I selected to NOT run the graphql API server when I installed the plugin.

```error  in ./src/main.js

Module build failed: Error: Error while loading rule 'graphql/template-strings': Must provide .graphqlconfig file or pass in `schemaJson` option with schema object or `schemaJsonFilepath` with absolute path to the json file.
    at parseOptions (/home/mekhami/Work/portaldemo/node_modules/eslint-plugin-graphql/lib/index.js:325:15)
    at /home/mekhami/Work/portaldemo/node_modules/eslint-plugin-graphql/lib/index.js:198:16
    at _loop (/home/mekhami/Work/portaldemo/node_modules/eslint-plugin-graphql/lib/index.js:83:27)
    at createRule (/home/mekhami/Work/portaldemo/node_modules/eslint-plugin-graphql/lib/index.js:102:7)
    at Object.create (/home/mekhami/Work/portaldemo/node_modules/eslint-plugin-graphql/lib/index.js:197:14)
    at createRuleListeners (/home/mekhami/Work/portaldemo/node_modules/eslint/lib/linter.js:682:21)
    at Object.keys.forEach.ruleId (/home/mekhami/Work/portaldemo/node_modules/eslint/lib/linter.js:841:31)
    at Array.forEach (<anonymous>)
    at runRules (/home/mekhami/Work/portaldemo/node_modules/eslint/lib/linter.js:781:34)
    at Linter._verifyWithoutProcessors (/home/mekhami/Work/portaldemo/node_modules/eslint/lib/linter.js:1003:33)
    at preprocess.map.textBlock (/home/mekhami/Work/portaldemo/node_modules/eslint/lib/linter.js:1046:35)
    at Array.map (<anonymous>)
    at Linter.verify (/home/mekhami/Work/portaldemo/node_modules/eslint/lib/linter.js:1045:42)
    at Linter.verifyAndFix (/home/mekhami/Work/portaldemo/node_modules/eslint/lib/linter.js:1138:29)
    at processText (/home/mekhami/Work/portaldemo/node_modules/eslint/lib/cli-engine.js:180:32)
    at CLIEngine.executeOnText (/home/mekhami/Work/portaldemo/node_modules/eslint/lib/cli-engine.js:620:17)

 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by Akryum** [comment]
You can comment/remove the relevant eslint config:

```js
plugins: [
  'graphql',
],
rules: {
  'graphql/template-strings': ['error', {
    env: 'literal',
  }],
},
```

Or you can [configure the plugin](https://github.com/apollographql/eslint-plugin-graphql#importing-schema-json) to suit your environment.

**Comment by Jancat** [comment]
run `vue-cli-service apollo:schema:generate` to generate **schema.json** in `node_modules/.temp/graphql/` path
