### ISSUE TITLE
vue-cli 3.0.0.beta.16: ERROR  TypeError: Cannot read property 'cacheIdentifier' of undefined

### ISSUE THREAD

**Issue by cannap** [Akryum/vue-cli-plugin-apollo#26]
hi i got that error

 ERROR  TypeError: Cannot read property 'cacheIdentifier' of undefined

```js

TypeError: Cannot read property 'cacheIdentifier' of undefined
    at config.module.rule.test.use.tap.options (C:\Users\marko\Desktop\graphqll\client\node_modules\vue-cli-plugin-apollo\index.js:49:36)
    at Object.tap (C:\Users\marko\Desktop\graphqll\client\node_modules\webpack-chain\src\Use.js:14:20)
    at api.chainWebpack.config (C:\Users\marko\Desktop\graphqll\client\node_modules\vue-cli-plugin-apollo\index.js:47:10)
    at webpackChainFns.forEach.fn (C:\Users\marko\Desktop\graphqll\client\node_modules\@vue\cli-service\lib\Service.js:173:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (C:\Users\marko\Desktop\graphqll\client\node_modules\@vue\cli-service\lib\Service.js:173:26)
    at Service.resolveWebpackConfig (C:\Users\marko\Desktop\graphqll\client\node_modules\@vue\cli-service\lib\Service.js:177:48)
    at PluginAPI.resolveWebpackConfig (C:\Users\marko\Desktop\graphqll\client\node_modules\@vue\cli-service\lib\PluginAPI.js:103:25)
    at serve (C:\Users\marko\Desktop\graphqll\client\node_modules\@vue\cli-service\lib\commands\serve.js:46:31)
    at Service.run (C:\Users\marko\Desktop\graphqll\client\node_modules\@vue\cli-service\lib\Service.js:167:12)
    at Object.<anonymous> (C:\Users\marko\Desktop\graphqll\client\node_modules\@vue\cli-service\bin\vue-cli-service.js:22:9)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
```

Current plugins: https://gyazo.com/6fa3cef27fc2016d447ead99591eec40

i dont know what happen :D

**Comment by cannap** [comment]
i found it 

when i enable eslint on save it starts working

https://www.useloom.com/share/95e7b62abdb6423eb4c956d9771772b0 

sry i am not sure this problem is eslint vue-cli or vue cli apollo plugin related :D

**Comment by thetre97** [comment]
I also get this issue, but similar to #25  if I use ESLint standard, with `lintOnSave: true` in vue config (as above), it works.
