### ISSUE TITLE
'vue-cli-plugin-apollo' should be listed in the project's dependencies

### ISSUE THREAD

**Issue by scleriot** [Akryum/vue-cli-plugin-apollo#28]
Hello,

I've created a project from scratch using vue-cli and the ts-vue preset. When I try adding the vue-cli-plugin-apollo (through vue-cli UI) I get the following error (after the configuration step) : 
```console
⠋  Running completion hooks...
error: 'vue-cli-plugin-apollo' should be listed in the project's dependencies, not devDependencies (import/no-extraneous-dependencies) at src/vue-apollo.js:3:1:
  1 | import Vue from 'vue';
  2 | import VueApollo from 'vue-apollo';
> 3 | import { createApolloClient, restartWebsockets } from 'vue-cli-plugin-apollo/graphql-client';
    | ^
  4 |
  5 | // Install the vue plugin
  6 | Vue.use(VueApollo);
```

Here is the full trace : 
```console
{"type":"warning","data":"../package.json: No license field"}
{"type":"warning","data":"\"@vue/cli-plugin-babel > babel-loader@8.0.0-beta.3\" has unmet peer dependency \"webpack@>=2\"."}
{"type":"warning","data":"\"@vue/cli-plugin-eslint > eslint-loader@2.0.0\" has unmet peer dependency \"webpack@>=2.0.0 <5.0.0\"."}
{"type":"warning","data":"\"@vue/cli-plugin-typescript > fork-ts-checker-webpack-plugin@0.4.2\" has unmet peer dependency \"webpack@^2.3.0 || ^3.0.0 || ^4.0.0\"."}
{"type":"warning","data":"\"@vue/eslint-config-airbnb > eslint-config-airbnb-base@12.1.0\" has unmet peer dependency \"eslint@^4.9.0\"."}
{"type":"warning","data":"\"@vue/eslint-config-airbnb > eslint-import-resolver-webpack@0.9.0\" has unmet peer dependency \"webpack@>=1.11.0\"."}
{"type":"warning","data":"\"@vue/eslint-config-airbnb > eslint-plugin-import@2.12.0\" has unmet peer dependency \"eslint@2.x - 4.x\"."}
{"type":"warning","data":"\"@vue/eslint-config-typescript > typescript-eslint-parser@16.0.0\" has unmet peer dependency \"typescript@*\"."}
{"type":"warning","data":"\" > sass-loader@7.0.3\" has unmet peer dependency \"webpack@^3.0.0 || ^4.0.0\"."}
{"type":"warning","data":"\"vue-cli-plugin-apollo > apollo-link-persisted-queries@0.2.0\" has incorrect peer dependency \"graphql@0.11.7\"."}
{"type":"warning","data":"\" > vue-cli-plugin-apollo@0.13.6\" has unmet peer dependency \"@vue/cli-shared-utils@^3.0.0-beta.11\"."}
{"type":"warning","data":"\" > vue-cli-plugin-apollo@0.13.6\" has unmet peer dependency \"chalk@^2.3.1\"."}
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.child.stdout.on.buffer (/Users/scleriot/.config/yarn/global/node_modules/@vue/cli/lib/util/installDeps.js:117:31)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
{"type":"tree","data":{"type":"newAllDependencies","trees":[{"name":"@babel/runtime@7.0.0-beta.49","children":[],"hint":null,"color":null,"depth":0},{"name":"vue-cli-plugin-apollo@0.13.6","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/graphql@0.12.6","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-engine@1.1.2","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-link-context@1.0.8","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-server-express@1.3.6","children":[],"hint":null,"color":null,"depth":0},{"name":"body-parser@1.18.3","children":[],"hint":null,"color":null,"depth":0},{"name":"cors@2.8.4","children":[],"hint":null,"color":null,"depth":0},{"name":"graphql@0.13.2","children":[],"hint":null,"color":null,"depth":0},{"name":"nodemon@1.17.5","children":[],"hint":null,"color":null,"depth":0},{"name":"zen-observable-ts@0.8.9","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-cache-inmemory@1.2.2","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-client@2.3.2","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-link-http@1.5.4","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-link-persisted-queries@0.2.0","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-link-state@0.4.1","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-link-ws@1.0.8","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-upload-client@8.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-upload-server@5.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"graphql-playground-middleware-express@1.7.0","children":[],"hint":null,"color":null,"depth":0},{"name":"graphql-subscriptions@0.5.8","children":[],"hint":null,"color":null,"depth":0},{"name":"graphql-tools@3.0.2","children":[],"hint":null,"color":null,"depth":0},{"name":"subscriptions-transport-ws@0.9.10","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/async@2.0.49","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/express@4.16.0","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/koa-bodyparser@4.2.0","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/koa-router@7.0.28","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/restify@5.0.9","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/zen-observable@0.5.3","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-engine-binary-darwin@0.2018.6-20-gc0e4bb519","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-engine-binary-linux@0.2018.6-20-gc0e4bb519","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-engine-binary-windows@0.2018.6-20-gc0e4bb519","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-link-dedup@1.0.9","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-server-module-graphiql@1.3.4","children":[],"hint":null,"color":null,"depth":0},{"name":"backo2@1.0.2","children":[],"hint":null,"color":null,"depth":0},{"name":"busboy@0.2.14","children":[],"hint":null,"color":null,"depth":0},{"name":"deprecated-decorator@0.1.6","children":[],"hint":null,"color":null,"depth":0},{"name":"extract-files@3.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"graphql-anywhere@4.1.11","children":[],"hint":null,"color":null,"depth":0},{"name":"graphql-playground-html@1.6.0","children":[],"hint":null,"color":null,"depth":0},{"name":"ignore-by-default@1.0.1","children":[],"hint":null,"color":null,"depth":0},{"name":"lodash.isobject@3.0.2","children":[],"hint":null,"color":null,"depth":0},{"name":"object-path@0.11.4","children":[],"hint":null,"color":null,"depth":0},{"name":"pstree.remy@1.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"raw-body@2.3.3","children":[],"hint":null,"color":null,"depth":0},{"name":"symbol-observable@1.2.0","children":[],"hint":null,"color":null,"depth":0},{"name":"touch@3.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"undefsafe@2.0.2","children":[],"hint":null,"color":null,"depth":0},{"name":"update-notifier@2.5.0","children":[],"hint":null,"color":null,"depth":0},{"name":"ws@5.2.0","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-link-http-common@0.2.4","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-server-core@1.3.6","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/accepts@1.3.5","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/body-parser@1.17.0","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/bunyan@1.8.4","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/cookies@0.7.1","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/http-assert@1.3.0","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/koa-compose@3.2.2","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/serve-static@1.13.2","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/spdy@3.4.4","children":[],"hint":null,"color":null,"depth":0},{"name":"async-limiter@1.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"boxen@1.3.0","children":[],"hint":null,"color":null,"depth":0},{"name":"configstore@3.1.2","children":[],"hint":null,"color":null,"depth":0},{"name":"dicer@0.2.5","children":[],"hint":null,"color":null,"depth":0},{"name":"import-lazy@2.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"is-installed-globally@0.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"is-npm@1.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"latest-version@3.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"ps-tree@1.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"semver-diff@2.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-cache-control@0.1.1","children":[],"hint":null,"color":null,"depth":0},{"name":"apollo-tracing@0.1.4","children":[],"hint":null,"color":null,"depth":0},{"name":"graphql-config@2.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"graphql-extensions@0.0.10","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/mime@2.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"@types/range-parser@1.2.2","children":[],"hint":null,"color":null,"depth":0},{"name":"ansi-align@2.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"cli-boxes@1.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"event-stream@3.3.4","children":[],"hint":null,"color":null,"depth":0},{"name":"global-dirs@0.1.1","children":[],"hint":null,"color":null,"depth":0},{"name":"graphql-request@1.6.0","children":[],"hint":null,"color":null,"depth":0},{"name":"package-json@4.0.1","children":[],"hint":null,"color":null,"depth":0},{"name":"source-map-support@0.5.6","children":[],"hint":null,"color":null,"depth":0},{"name":"streamsearch@0.1.2","children":[],"hint":null,"color":null,"depth":0},{"name":"term-size@1.2.0","children":[],"hint":null,"color":null,"depth":0},{"name":"unique-string@1.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"widest-line@2.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"write-file-atomic@2.3.0","children":[],"hint":null,"color":null,"depth":0},{"name":"graphql-import@0.4.5","children":[],"hint":null,"color":null,"depth":0},{"name":"cross-fetch@2.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"crypto-random-string@1.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"from@0.1.7","children":[],"hint":null,"color":null,"depth":0},{"name":"got@6.7.1","children":[],"hint":null,"color":null,"depth":0},{"name":"map-stream@0.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"pause-stream@0.0.11","children":[],"hint":null,"color":null,"depth":0},{"name":"registry-auth-token@3.3.2","children":[],"hint":null,"color":null,"depth":0},{"name":"registry-url@3.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"split@0.3.3","children":[],"hint":null,"color":null,"depth":0},{"name":"stream-combiner@0.0.4","children":[],"hint
":null,"color":null,"depth":0},{"name":"create-error-class@3.0.2","children":[],"hint":null,"color":null,"depth":0},{"name":"duplexer3@0.1.4","children":[],"hint":null,"color":null,"depth":0},{"name":"is-redirect@1.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"is-retry-allowed@1.1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"lowercase-keys@1.0.1","children":[],"hint":null,"color":null,"depth":0},{"name":"node-fetch@2.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"timed-out@4.0.1","children":[],"hint":null,"color":null,"depth":0},{"name":"unzip-response@2.0.1","children":[],"hint":null,"color":null,"depth":0},{"name":"url-parse-lax@1.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"whatwg-fetch@2.0.3","children":[],"hint":null,"color":null,"depth":0},{"name":"capture-stack-trace@1.0.0","children":[],"hint":null,"color":null,"depth":0}]}}

🚀  Invoking generator for vue-cli-plugin-apollo...
⠸  Installing additional dependencies...{"type":"warning","data":"../package.json: No license field"}
⠋  Installing additional dependencies...{"type":"warning","data":"\" > vue-apollo@3.0.0-beta.16\" has unmet peer dependency \"apollo-client@^2.0.0\"."}
{"type":"warning","data":"\"@vue/cli-plugin-babel > babel-loader@8.0.0-beta.3\" has unmet peer dependency \"webpack@>=2\"."}
{"type":"warning","data":"\"@vue/cli-plugin-eslint > eslint-loader@2.0.0\" has unmet peer dependency \"webpack@>=2.0.0 <5.0.0\"."}
⠙  Installing additional dependencies...{"type":"warning","data":"\"@vue/cli-plugin-typescript > fork-ts-checker-webpack-plugin@0.4.2\" has unmet peer dependency \"webpack@^2.3.0 || ^3.0.0 || ^4.0.0\"."}
⠹  Installing additional dependencies...{"type":"warning","data":"\"@vue/eslint-config-airbnb > eslint-config-airbnb-base@12.1.0\" has unmet peer dependency \"eslint@^4.9.0\"."}
{"type":"warning","data":"\"@vue/eslint-config-airbnb > eslint-import-resolver-webpack@0.9.0\" has unmet peer dependency \"webpack@>=1.11.0\"."}
{"type":"warning","data":"\"@vue/eslint-config-airbnb > eslint-plugin-import@2.12.0\" has unmet peer dependency \"eslint@2.x - 4.x\"."}
{"type":"warning","data":"\"@vue/eslint-config-typescript > typescript-eslint-parser@16.0.0\" has unmet peer dependency \"typescript@*\"."}
{"type":"warning","data":"\" > graphql-tag@2.9.2\" has unmet peer dependency \"graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0\"."}
{"type":"warning","data":"\" > sass-loader@7.0.3\" has unmet peer dependency \"webpack@^3.0.0 || ^4.0.0\"."}
{"type":"warning","data":"\" > vue-cli-plugin-apollo@0.13.6\" has unmet peer dependency \"@vue/cli-shared-utils@^3.0.0-beta.11\"."}
{"type":"warning","data":"\" > vue-cli-plugin-apollo@0.13.6\" has unmet peer dependency \"chalk@^2.3.1\"."}
⠸  Installing additional dependencies...{"type":"warning","data":"\"vue-cli-plugin-apollo > apollo-link-persisted-queries@0.2.0\" has incorrect peer dependency \"graphql@0.11.7\"."}
📦  Installing additional dependencies...
⠋  Running completion hooks...error: 'vue-cli-plugin-apollo' should be listed in the project's dependencies, not devDependencies (import/no-extraneous-dependencies) at src/vue-apollo.js:3:1:
  1 | import Vue from 'vue';
  2 | import VueApollo from 'vue-apollo';
> 3 | import { createApolloClient, restartWebsockets } from 'vue-cli-plugin-apollo/graphql-client';
    | ^
  4 |
  5 | // Install the vue plugin
  6 | Vue.use(VueApollo);
```

I've tried using vue-cli beta15 and beta16

**Comment by Akryum** [comment]
You will need to move it yourself, as vue cli plugins are installed as devDepedencies.

**Comment by betweenbrain** [comment]
Just for the sake of documenting this, `npm install vue-cli-plugin-apollo --save-prod` may be the easiest way to do this. Or, at least, one easy way to do it.

**Comment by ouahibAbdou** [comment]
@Akryum man if u wanna make something make it clear.
This is a joke
