### ISSUE TITLE
ERROR  Error: Type "Upload" was defined more than once.

### ISSUE THREAD

**Issue by L-K-Mist** [Akryum/vue-cli-plugin-apollo#33]
Following exactly the install steps (including the graphql server api) - after your fascinating presentation at VueConf Amsterdam.           All works well up to the point of `npm run apollo`  Any idea what's going wrong?    Error paste below:

`` ERROR  Error: Type "Upload" was defined more than once.
Error: Type "Upload" was defined more than once.
    at Object.buildASTSchema (/home/dylan/CodeWorkspace/my-new-app/node_modules/graphql/utilities/buildASTSchema.js:116:17)
    at Object.buildSchemaFromTypeDefinitions (/home/dylan/CodeWorkspace/my-new-app/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:24:28)
    at _generateSchema (/home/dylan/CodeWorkspace/my-new-app/node_modules/graphql-tools/dist/makeExecutableSchema.js:29:29)
    at Object.makeExecutableSchema (/home/dylan/CodeWorkspace/my-new-app/node_modules/graphql-tools/dist/makeExecutableSchema.js:47:20)
    at new ApolloServerBase (/home/dylan/CodeWorkspace/my-new-app/node_modules/apollo-server-core/dist/ApolloServer.js:89:31)
    at new ApolloServer (/home/dylan/CodeWorkspace/my-new-app/node_modules/apollo-server-express/dist/ApolloServer.js:41:1)
    at module.exports (/home/dylan/CodeWorkspace/my-new-app/node_modules/vue-cli-plugin-apollo/graphql-server/index.js:127:18)
    at run (/home/dylan/CodeWorkspace/my-new-app/node_modules/vue-cli-plugin-apollo/index.js:164:7)
    at api.registerCommand.args (/home/dylan/CodeWorkspace/my-new-app/node_modules/vue-cli-plugin-apollo/index.js:176:7)
    at Service.run (/home/dylan/CodeWorkspace/my-new-app/node_modules/@vue/cli-service/lib/Service.js:179:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-new-app@0.1.0 apollo:run: `vue-cli-service apollo:run`
npm ERR! Exit status 1
npm ERR!``

**Comment by L-K-Mist** [comment]
Wow, looks like you climbed straight in there and fixed it. :+1:  Will check during the day tomorrow (it's bedtime for me here in South Africa ;)  )

**Comment by L-K-Mist** [comment]
Excellent, thank you. Problem solved. :+1:
