### ISSUE TITLE
TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by mathieutu** [Akryum/vue-cli-plugin-apollo#45]
Hi @Akryum!

Several times, don't know why, when watching the server, I've this error: 
```shell
⏳  GraphQL API is restarting...
$ vue-cli-service apollo:run --delay
/Users/mathieutu/Projects/askip/node_modules/@vue/cli-shared-utils/lib/ipc.js:41
      ipc.of[this.id].emit(type, data)
                      ^

TypeError: Cannot read property 'emit' of undefined
    at IpcMessenger.send (/Users/mathieutu/Projects/askip/node_modules/@vue/cli-shared-utils/lib/ipc.js:41:23)
    at IpcMessenger.disconnect (/Users/mathieutu/Projects/askip/node_modules/@vue/cli-shared-utils/lib/ipc.js:80:10)
    at Timeout.setTimeout [as _onTimeout] (/Users/mathieutu/Projects/askip/node_modules/vue-cli-plugin-apollo/index.js:229:11)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
error Command failed with exit code 1.
```

Usually I restart the server, and it's ok.
Any idea?

**Comment by Akryum** [comment]
It will be fixed in the next release of vue-cli.

**Comment by mathieutu** [comment]
Thx!

**Comment by mathieutu** [comment]
Found this issue, no idea if it's work, but it's old now so I'm closing that.
